// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgePerfLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

FBridgeLumenDiagnostics UUnrealBridgePerfLibrary::GetLumenDiagnostics()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::GetLumenDiagnostics requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeLumenDiagnostics{};
}

FBridgeNaniteStats UUnrealBridgePerfLibrary::GetNaniteStats()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::GetNaniteStats requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNaniteStats{};
}

FBridgePerfTraceSummary UUnrealBridgePerfLibrary::ParseTraceToSummary(
	const FString& UtracePath,
	int32 TopN,
	int32 TopNPerThread,
	int32 TopNCounters)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::ParseTraceToSummary requires UE 5.7+ — call ignored on this engine version"));
	return FBridgePerfTraceSummary{};
}

FBridgePerfAllocSummary UUnrealBridgePerfLibrary::ParseAllocTraceToSummary(const FString& UtracePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::ParseAllocTraceToSummary requires UE 5.7+ — call ignored on this engine version"));
	return FBridgePerfAllocSummary{};
}

FBridgePerfNetSummary UUnrealBridgePerfLibrary::ParseNetTraceToSummary(const FString& UtracePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::ParseNetTraceToSummary requires UE 5.7+ — call ignored on this engine version"));
	return FBridgePerfNetSummary{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
